using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.ComponentModel.DataAnnotations;
using DevExpress.XtraBars;
using System.Data.Entity;

namespace BHXH.List.UI
{
    public partial class frmListNationlity : XtraForm
    {
        public frmListNationlity()
        {
            InitializeComponent();
            //     dataGridView1.AutoGenerateColumns = true;
            //    dataGridView1.DataSource = BHXH.List.Business.ListNationality.GetAll().ToList();
            //       label1.Text = dataGridView1.Columns[0].HeaderText;
            //  label2.Text = dataGridView1.Columns[1].HeaderText;



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            BHXH.Data.BHXH dbContext = new BHXH.Data.BHXH();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.ListNationality.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl2.DataSource = dbContext.ListNationality.Local.ToBindingList();
        }


        private void gridControl_Click(object sender, EventArgs e)
        {
           
        }

        private void labelControl_Click(object sender, EventArgs e)
        {

        }

        private void windowsUIButtonPanel_Click(object sender, EventArgs e)
        {
            frmNewNationlity f = new frmNewNationlity();
            
            f.ShowDialog();
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void windowsUIButtonPanel1_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonGhi_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonQua_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonThoat_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonIn_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonXoa_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonSua_Click(object sender, EventArgs e)
        {

        }

        private void SimpleButtonMoi_Click(object sender, EventArgs e)
        {

        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }
    }
}
