//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BHXH : DbContext
    {
        public BHXH()
            : base("name=BHXH")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListBangCap> ListBangCap { get; set; }
        public virtual DbSet<ListCapKTKL> ListCapKTKL { get; set; }
        public virtual DbSet<ListCMDaoTao> ListCMDaoTao { get; set; }
        public virtual DbSet<ListCommunes> ListCommunes { get; set; }
        public virtual DbSet<ListChiBo> ListChiBo { get; set; }
        public virtual DbSet<ListChucDanh> ListChucDanh { get; set; }
        public virtual DbSet<ListChucVu> ListChucVu { get; set; }
        public virtual DbSet<ListChucVuDang> ListChucVuDang { get; set; }
        public virtual DbSet<ListDienCS> ListDienCS { get; set; }
        public virtual DbSet<ListDistricts> ListDistricts { get; set; }
        public virtual DbSet<ListEthnics> ListEthnics { get; set; }
        public virtual DbSet<ListHonNhan> ListHonNhan { get; set; }
        public virtual DbSet<ListHopDong> ListHopDong { get; set; }
        public virtual DbSet<ListKTKL> ListKTKL { get; set; }
        public virtual DbSet<ListLHDaoTao> ListLHDaoTao { get; set; }
        public virtual DbSet<ListLoaiTB> ListLoaiTB { get; set; }
        public virtual DbSet<ListNationality> ListNationality { get; set; }
        public virtual DbSet<ListNoiKCB> ListNoiKCB { get; set; }
        public virtual DbSet<ListNganHang> ListNganHang { get; set; }
        public virtual DbSet<ListNghiepVu> ListNghiepVu { get; set; }
        public virtual DbSet<ListNgoaiNgu> ListNgoaiNgu { get; set; }
        public virtual DbSet<ListProvinces> ListProvinces { get; set; }
        public virtual DbSet<ListPhongBan> ListPhongBan { get; set; }
        public virtual DbSet<ListQuan> ListQuan { get; set; }
        public virtual DbSet<ListQuanHeGD> ListQuanHeGD { get; set; }
        public virtual DbSet<ListQuocGia> ListQuocGia { get; set; }
        public virtual DbSet<ListTDDaoTao> ListTDDaoTao { get; set; }
        public virtual DbSet<ListTDLLCT> ListTDLLCT { get; set; }
        public virtual DbSet<ListTDNgoaiNgu> ListTDNgoaiNgu { get; set; }
        public virtual DbSet<ListTDQLNN> ListTDQLNN { get; set; }
        public virtual DbSet<ListTDVanHoa> ListTDVanHoa { get; set; }
        public virtual DbSet<ListTonGiao> ListTonGiao { get; set; }
        public virtual DbSet<ListThanhPhanGD> ListThanhPhanGD { get; set; }
    
        public virtual int DBA_RestoreDB(string p_strDBNameTo, string p_strDBNameFrom, string p_strFQNRestoreFileName)
        {
            var p_strDBNameToParameter = p_strDBNameTo != null ?
                new ObjectParameter("p_strDBNameTo", p_strDBNameTo) :
                new ObjectParameter("p_strDBNameTo", typeof(string));
    
            var p_strDBNameFromParameter = p_strDBNameFrom != null ?
                new ObjectParameter("p_strDBNameFrom", p_strDBNameFrom) :
                new ObjectParameter("p_strDBNameFrom", typeof(string));
    
            var p_strFQNRestoreFileNameParameter = p_strFQNRestoreFileName != null ?
                new ObjectParameter("p_strFQNRestoreFileName", p_strFQNRestoreFileName) :
                new ObjectParameter("p_strFQNRestoreFileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DBA_RestoreDB", p_strDBNameToParameter, p_strDBNameFromParameter, p_strFQNRestoreFileNameParameter);
        }
    }
}
