//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BHXHEntities : DbContext
    {
        public BHXHEntities()
            : base("name=BHXHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ListCommunes> ListCommunes { get; set; }
        public virtual DbSet<ListDistricts> ListDistricts { get; set; }
        public virtual DbSet<ListEthnics> ListEthnics { get; set; }
        public virtual DbSet<ListNationality> ListNationality { get; set; }
        public virtual DbSet<ListProvinces> ListProvinces { get; set; }
    
        public virtual int DBA_RestoreDB(string p_strDBNameTo, string p_strDBNameFrom, string p_strFQNRestoreFileName)
        {
            var p_strDBNameToParameter = p_strDBNameTo != null ?
                new ObjectParameter("p_strDBNameTo", p_strDBNameTo) :
                new ObjectParameter("p_strDBNameTo", typeof(string));
    
            var p_strDBNameFromParameter = p_strDBNameFrom != null ?
                new ObjectParameter("p_strDBNameFrom", p_strDBNameFrom) :
                new ObjectParameter("p_strDBNameFrom", typeof(string));
    
            var p_strFQNRestoreFileNameParameter = p_strFQNRestoreFileName != null ?
                new ObjectParameter("p_strFQNRestoreFileName", p_strFQNRestoreFileName) :
                new ObjectParameter("p_strFQNRestoreFileName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DBA_RestoreDB", p_strDBNameToParameter, p_strDBNameFromParameter, p_strFQNRestoreFileNameParameter);
        }
    
        public virtual int GETQUATRINH(string sOBHXH)
        {
            var sOBHXHParameter = sOBHXH != null ?
                new ObjectParameter("SOBHXH", sOBHXH) :
                new ObjectParameter("SOBHXH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GETQUATRINH", sOBHXHParameter);
        }
    
        public virtual int thu(string soBHXH)
        {
            var soBHXHParameter = soBHXH != null ?
                new ObjectParameter("SoBHXH", soBHXH) :
                new ObjectParameter("SoBHXH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("thu", soBHXHParameter);
        }
    
        public virtual int UpdateSoSo(string soso, string fullName, Nullable<System.DateTime> birthday)
        {
            var sosoParameter = soso != null ?
                new ObjectParameter("soso", soso) :
                new ObjectParameter("soso", typeof(string));
    
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSoSo", sosoParameter, fullNameParameter, birthdayParameter);
        }
    
        public virtual int XemQuaTrinh(string fullName, Nullable<System.DateTime> birthday)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XemQuaTrinh", fullNameParameter, birthdayParameter);
        }
    
        public virtual int XemQuaTrinhNew(string fullName, Nullable<System.DateTime> birthday)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XemQuaTrinhNew", fullNameParameter, birthdayParameter);
        }
    
        public virtual int XemQuaTrinhNewAll(string fullName, Nullable<System.DateTime> birthday, string soBHXH, string sOCMND)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("FullName", fullName) :
                new ObjectParameter("FullName", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var soBHXHParameter = soBHXH != null ?
                new ObjectParameter("SoBHXH", soBHXH) :
                new ObjectParameter("SoBHXH", typeof(string));
    
            var sOCMNDParameter = sOCMND != null ?
                new ObjectParameter("SOCMND", sOCMND) :
                new ObjectParameter("SOCMND", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XemQuaTrinhNewAll", fullNameParameter, birthdayParameter, soBHXHParameter, sOCMNDParameter);
        }
    
        public virtual int XemQuaTrinhThatNghiep(string sobhxh)
        {
            var sobhxhParameter = sobhxh != null ?
                new ObjectParameter("Sobhxh", sobhxh) :
                new ObjectParameter("Sobhxh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XemQuaTrinhThatNghiep", sobhxhParameter);
        }
    }
}
