//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrChiTietDaoTao
    {
        public System.Guid MaNhanVien { get; set; }
        public string MaCMDaoTao { get; set; }
        public string TenTruong { get; set; }
        public string NganhHoc { get; set; }
        public string ThoiGian { get; set; }
        public string MaLHDaoTao { get; set; }
        public string MaBangCap { get; set; }
        public string XepLoai { get; set; }
        public System.Guid QuaTrinhDaoTaoID { get; set; }
        public Nullable<decimal> STT { get; set; }
    
        public virtual ListBangCap ListBangCap { get; set; }
        public virtual ListCMDaoTao ListCMDaoTao { get; set; }
        public virtual ListLHDaoTao ListLHDaoTao { get; set; }
        public virtual HrNhanVien HrNhanVien { get; set; }
    }
}
