//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrLuongToiThieu
    {
        public Nullable<System.DateTime> NgayTu { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<decimal> MucLuong { get; set; }
        public System.Guid LuongToiThieuID { get; set; }
    }
}
