//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrNgayCong
    {
        public string Nam { get; set; }
        public Nullable<decimal> Thang01 { get; set; }
        public Nullable<decimal> Thang02 { get; set; }
        public Nullable<decimal> Thang03 { get; set; }
        public Nullable<decimal> Thang04 { get; set; }
        public Nullable<decimal> Thang05 { get; set; }
        public Nullable<decimal> Thang06 { get; set; }
        public Nullable<decimal> Thang07 { get; set; }
        public Nullable<decimal> Thang08 { get; set; }
        public Nullable<decimal> Thang09 { get; set; }
        public Nullable<decimal> Thang10 { get; set; }
        public Nullable<decimal> Thang11 { get; set; }
        public Nullable<decimal> Thang12 { get; set; }
        public System.Guid NgayCongID { get; set; }
    }
}
