//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrNhanVien()
        {
            this.HrKhenThuongKyLuat = new HashSet<HrKhenThuongKyLuat>();
            this.HrPSBHXH = new HashSet<HrPSBHXH>();
            this.HrPSLuong = new HashSet<HrPSLuong>();
            this.HrQuanHeGiaDinh = new HashSet<HrQuanHeGiaDinh>();
            this.HrQuaTrinhBHXH = new HashSet<HrQuaTrinhBHXH>();
            this.HrQuaTrinhLuong = new HashSet<HrQuaTrinhLuong>();
            this.SysUser = new HashSet<SysUser>();
        }
    
        public System.Guid MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string MaPhongBan { get; set; }
        public string SoHieuNV { get; set; }
        public string GioiTinh { get; set; }
        public string TenKhac { get; set; }
        public string MaCapUy { get; set; }
        public string MaCapUyKiem { get; set; }
        public string MaChucVu { get; set; }
        public string MaChucDanh { get; set; }
        public Nullable<decimal> PCChucVu { get; set; }
        public Nullable<System.DateTime> NgayBoNhiem { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string MaTinhQQ { get; set; }
        public Nullable<decimal> QuanHuyenIDQQ { get; set; }
        public Nullable<decimal> XaPhuongIDQQ { get; set; }
        public string MatinhTQ { get; set; }
        public Nullable<decimal> QuanHuyenIDTQ { get; set; }
        public Nullable<decimal> XaPhuongIDTQ { get; set; }
        public string SoNha { get; set; }
        public string DTNha { get; set; }
        public string DTCoQuan { get; set; }
        public string DTDiDong { get; set; }
        public string Email { get; set; }
        public string DTNguoiNha { get; set; }
        public string TenNguoiNha { get; set; }
        public string MaDanToc { get; set; }
        public string MaTonGiao { get; set; }
        public string MaThanhPhanGD { get; set; }
        public string NgheTruocTD { get; set; }
        public Nullable<System.DateTime> NgayTD { get; set; }
        public Nullable<System.DateTime> NgayCQ { get; set; }
        public string CoQuanTD { get; set; }
        public Nullable<System.DateTime> NgayCM { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayDangCT { get; set; }
        public Nullable<System.DateTime> NgayTCXH { get; set; }
        public Nullable<System.DateTime> NgayNhapNgu { get; set; }
        public Nullable<System.DateTime> NgayXuatNgu { get; set; }
        public string QuanHam { get; set; }
        public string MaTDVanHoa { get; set; }
        public string MaTDDaoTao { get; set; }
        public string MaTDLLCT { get; set; }
        public string MaNgoaiNgu { get; set; }
        public string MaTDNgoaiNgu { get; set; }
        public string CVDangLam { get; set; }
        public string MaNgach { get; set; }
        public string Bac { get; set; }
        public Nullable<decimal> HSL { get; set; }
        public string DHDuocPhong { get; set; }
        public string SoTruongCT { get; set; }
        public string CVLamLN { get; set; }
        public string KhenThuong { get; set; }
        public string KyLuat { get; set; }
        public string SucKhoe { get; set; }
        public string ChieuCao { get; set; }
        public string CanNang { get; set; }
        public string NhomMau { get; set; }
        public string SoCMND { get; set; }
        public string MaLoaiTB { get; set; }
        public Nullable<bool> GDLietSy { get; set; }
        public string TuDay { get; set; }
        public string CheDoCu { get; set; }
        public string TCNuocNgoai { get; set; }
        public string TNNuocNgoai { get; set; }
        public string SoBHXH { get; set; }
        public string TheBHYT { get; set; }
        public string MaTinhKCB { get; set; }
        public string MaNoiKCB { get; set; }
        public string TaiKhoanATM { get; set; }
        public string MaNganHang { get; set; }
        public Nullable<System.DateTime> NgayCMND { get; set; }
        public string NoiCMND { get; set; }
        public Nullable<System.DateTime> NgayNangLuong { get; set; }
        public Nullable<bool> DaNLTruocTH { get; set; }
        public byte[] AnhNV { get; set; }
        public string MaChiBo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrKhenThuongKyLuat> HrKhenThuongKyLuat { get; set; }
        public virtual ListChucVuDang ListChucVuDang { get; set; }
        public virtual ListChucVuDang ListChucVuDang1 { get; set; }
        public virtual ListChucVuDang ListChucVuDang2 { get; set; }
        public virtual ListChucVuDang ListChucVuDang3 { get; set; }
        public virtual ListChucVuDang ListChucVuDang4 { get; set; }
        public virtual ListChucVuDang ListChucVuDang5 { get; set; }
        public virtual ListChucVuDang ListChucVuDang6 { get; set; }
        public virtual ListChucVuDang ListChucVuDang7 { get; set; }
        public virtual ListChucDanh ListChucDanh { get; set; }
        public virtual ListChucDanh ListChucDanh1 { get; set; }
        public virtual ListChucDanh ListChucDanh2 { get; set; }
        public virtual ListChucDanh ListChucDanh3 { get; set; }
        public virtual ListDanToc ListDanToc { get; set; }
        public virtual ListDanToc ListDanToc1 { get; set; }
        public virtual ListDanToc ListDanToc2 { get; set; }
        public virtual ListDanToc ListDanToc3 { get; set; }
        public virtual ListNganHang ListNganHang { get; set; }
        public virtual ListNganHang ListNganHang1 { get; set; }
        public virtual HrThangBangLuong HrThangBangLuong { get; set; }
        public virtual HrThangBangLuong HrThangBangLuong1 { get; set; }
        public virtual ListNganHang ListNganHang2 { get; set; }
        public virtual ListNganHang ListNganHang3 { get; set; }
        public virtual HrThangBangLuong HrThangBangLuong2 { get; set; }
        public virtual HrThangBangLuong HrThangBangLuong3 { get; set; }
        public virtual ListNgoaiNgu ListNgoaiNgu { get; set; }
        public virtual ListNgoaiNgu ListNgoaiNgu1 { get; set; }
        public virtual ListNgoaiNgu ListNgoaiNgu2 { get; set; }
        public virtual ListNgoaiNgu ListNgoaiNgu3 { get; set; }
        public virtual ListPhongBan ListPhongBan { get; set; }
        public virtual ListPhongBan ListPhongBan1 { get; set; }
        public virtual ListPhongBan ListPhongBan2 { get; set; }
        public virtual ListPhongBan ListPhongBan3 { get; set; }
        public virtual ListTDDaoTao ListTDDaoTao { get; set; }
        public virtual ListTDDaoTao ListTDDaoTao1 { get; set; }
        public virtual ListTDDaoTao ListTDDaoTao2 { get; set; }
        public virtual ListTDDaoTao ListTDDaoTao3 { get; set; }
        public virtual ListTDLLCT ListTDLLCT { get; set; }
        public virtual ListTDLLCT ListTDLLCT1 { get; set; }
        public virtual ListTDLLCT ListTDLLCT2 { get; set; }
        public virtual ListTDLLCT ListTDLLCT3 { get; set; }
        public virtual ListTDNgoaiNgu ListTDNgoaiNgu { get; set; }
        public virtual ListTDNgoaiNgu ListTDNgoaiNgu1 { get; set; }
        public virtual ListTDNgoaiNgu ListTDNgoaiNgu2 { get; set; }
        public virtual ListTDNgoaiNgu ListTDNgoaiNgu3 { get; set; }
        public virtual ListTDVanHoa ListTDVanHoa { get; set; }
        public virtual ListTDVanHoa ListTDVanHoa1 { get; set; }
        public virtual ListTDVanHoa ListTDVanHoa2 { get; set; }
        public virtual ListTDVanHoa ListTDVanHoa3 { get; set; }
        public virtual ListTinh ListTinh { get; set; }
        public virtual ListTinh ListTinh1 { get; set; }
        public virtual ListTinh ListTinh2 { get; set; }
        public virtual ListTinh ListTinh3 { get; set; }
        public virtual ListTinh ListTinh4 { get; set; }
        public virtual ListTinh ListTinh5 { get; set; }
        public virtual ListTinh ListTinh6 { get; set; }
        public virtual ListTinh ListTinh7 { get; set; }
        public virtual ListTinh ListTinh8 { get; set; }
        public virtual ListTinh ListTinh9 { get; set; }
        public virtual ListTinh ListTinh10 { get; set; }
        public virtual ListTinh ListTinh11 { get; set; }
        public virtual ListTonGiao ListTonGiao { get; set; }
        public virtual ListTonGiao ListTonGiao1 { get; set; }
        public virtual ListTonGiao ListTonGiao2 { get; set; }
        public virtual ListTonGiao ListTonGiao3 { get; set; }
        public virtual ListThanhPhanGD ListThanhPhanGD { get; set; }
        public virtual ListThanhPhanGD ListThanhPhanGD1 { get; set; }
        public virtual ListThanhPhanGD ListThanhPhanGD2 { get; set; }
        public virtual ListThanhPhanGD ListThanhPhanGD3 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen1 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen2 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen3 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen4 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen5 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen6 { get; set; }
        public virtual ListQuanHuyen ListQuanHuyen7 { get; set; }
        public virtual ListXaPhuong ListXaPhuong { get; set; }
        public virtual ListXaPhuong ListXaPhuong1 { get; set; }
        public virtual ListXaPhuong ListXaPhuong2 { get; set; }
        public virtual ListXaPhuong ListXaPhuong3 { get; set; }
        public virtual ListXaPhuong ListXaPhuong4 { get; set; }
        public virtual ListXaPhuong ListXaPhuong5 { get; set; }
        public virtual ListXaPhuong ListXaPhuong6 { get; set; }
        public virtual ListXaPhuong ListXaPhuong7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPSBHXH> HrPSBHXH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPSLuong> HrPSLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrQuanHeGiaDinh> HrQuanHeGiaDinh { get; set; }
        public virtual HrQuaTrinhCongTac HrQuaTrinhCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrQuaTrinhBHXH> HrQuaTrinhBHXH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrQuaTrinhLuong> HrQuaTrinhLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUser> SysUser { get; set; }
    }
}
