//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrNhanVien
    {
        public System.Guid MaNhanVien { get; set; }
        public string TenNhanVien { get; set; }
        public string MaPhongBan { get; set; }
        public string SoHieuNV { get; set; }
        public string GioiTinh { get; set; }
        public string TenKhac { get; set; }
        public string MaCapUy { get; set; }
        public string MaCapUyKiem { get; set; }
        public string MaChucVu { get; set; }
        public string MaChucDanh { get; set; }
        public Nullable<decimal> PCChucVu { get; set; }
        public Nullable<System.DateTime> NgayBoNhiem { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string NoiSinh { get; set; }
        public string MaTinhQQ { get; set; }
        public string MaQuanQQ { get; set; }
        public string MaphuongQQ { get; set; }
        public string MatinhTQ { get; set; }
        public string MaQuanTQ { get; set; }
        public string MaPhuongTQ { get; set; }
        public string SoNha { get; set; }
        public string DTNha { get; set; }
        public string DTCoQuan { get; set; }
        public string DTDiDong { get; set; }
        public string Email { get; set; }
        public string DTNguoiNha { get; set; }
        public string TenNguoiNha { get; set; }
        public string MaDanToc { get; set; }
        public string MaTonGiao { get; set; }
        public string MaThanhPhanGD { get; set; }
        public string NgheTruocTD { get; set; }
        public Nullable<System.DateTime> NgayTD { get; set; }
        public Nullable<System.DateTime> NgayCQ { get; set; }
        public string CoQuanTD { get; set; }
        public Nullable<System.DateTime> NgayCM { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<System.DateTime> NgayDangCT { get; set; }
        public string MaChiBo { get; set; }
        public Nullable<System.DateTime> NgayTCXH { get; set; }
        public Nullable<System.DateTime> NgayNhapNgu { get; set; }
        public Nullable<System.DateTime> NgayXuatNgu { get; set; }
        public string QuanHam { get; set; }
        public string MaTDVanHoa { get; set; }
        public string MaTDDaoTao { get; set; }
        public string MaTDLLCT { get; set; }
        public string MaNgoaiNgu { get; set; }
        public string MaTDNgoaiNgu { get; set; }
        public string CVDangLam { get; set; }
        public string MaNgach { get; set; }
        public string Bac { get; set; }
        public Nullable<decimal> HSL { get; set; }
        public string DHDuocPhong { get; set; }
        public string SoTruongCT { get; set; }
        public string CVLamLN { get; set; }
        public string KhenThuong { get; set; }
        public string KyLuat { get; set; }
        public string SucKhoe { get; set; }
        public string ChieuCao { get; set; }
        public string CanNang { get; set; }
        public string NhomMau { get; set; }
        public string SoCMND { get; set; }
        public Nullable<decimal> MaLoaiTB { get; set; }
        public Nullable<bool> GDLietSy { get; set; }
        public string TuDay { get; set; }
        public string CheDoCu { get; set; }
        public string TCNuocNgoai { get; set; }
        public string TNNuocNgoai { get; set; }
        public string SoBHXH { get; set; }
        public string TheBHYT { get; set; }
        public string MaTinhKCB { get; set; }
        public string MaNoiKCB { get; set; }
        public string TaiKhoanATM { get; set; }
        public string MaNganHang { get; set; }
        public Nullable<System.DateTime> NgayCMND { get; set; }
        public string NoiCMND { get; set; }
        public Nullable<System.DateTime> NgayNangLuong { get; set; }
        public Nullable<bool> DaNLTruocTH { get; set; }
        public byte[] AnhNV { get; set; }
    }
}
