//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrPSLuong
    {
        public string Thang { get; set; }
        public string Nam { get; set; }
        public System.Guid MaNhanVien { get; set; }
        public Nullable<decimal> IDNgach { get; set; }
        public string Bac { get; set; }
        public Nullable<decimal> HSL { get; set; }
        public Nullable<decimal> MucLuong { get; set; }
        public string CongTacPhi { get; set; }
        public Nullable<decimal> PCChucVu { get; set; }
        public Nullable<decimal> PCTrachNhiem { get; set; }
        public Nullable<decimal> PCThamNien { get; set; }
        public Nullable<decimal> PCDocHai { get; set; }
        public string TuThang { get; set; }
        public string DenThang { get; set; }
        public string LoaiPS { get; set; }
        public Nullable<decimal> IDPhongNL { get; set; }
    }
}
