//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrQuaTrinhLuong
    {
        public System.Guid MaNhanVien { get; set; }
        public Nullable<decimal> STT { get; set; }
        public string Loai { get; set; }
        public string TuThang { get; set; }
        public string DenThang { get; set; }
        public Nullable<decimal> SoThang { get; set; }
        public Nullable<decimal> MucLuong { get; set; }
        public Nullable<decimal> HSL { get; set; }
        public Nullable<decimal> PCChucVu { get; set; }
        public Nullable<decimal> PCThamNien { get; set; }
        public Nullable<decimal> PCDocHai { get; set; }
        public Nullable<decimal> PCTrachNhiem { get; set; }
        public Nullable<decimal> PCKhuVuc { get; set; }
        public string CongViec { get; set; }
    }
}
