//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrQuaTrinhCongTac
    {
        public System.Guid MaNhanVien { get; set; }
        public Nullable<decimal> STT { get; set; }
        public string ThoiGian { get; set; }
        public string CongViec { get; set; }
        public Nullable<System.Guid> QuaTrinhCongTacID { get; set; }
    
        public virtual HrNhanVien HrNhanVien { get; set; }
    }
}
