//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrThangBangLuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrThangBangLuong()
        {
            this.HrNhanVien = new HashSet<HrNhanVien>();
            this.HrNhanVien1 = new HashSet<HrNhanVien>();
            this.HrNhanVien2 = new HashSet<HrNhanVien>();
            this.HrNhanVien3 = new HashSet<HrNhanVien>();
            this.HrPSBHXH = new HashSet<HrPSBHXH>();
        }
    
        public string MaNgach { get; set; }
        public string TenNgach { get; set; }
        public Nullable<decimal> ThangNL { get; set; }
        public Nullable<decimal> TongBac { get; set; }
        public Nullable<decimal> Bac01 { get; set; }
        public Nullable<decimal> Bac02 { get; set; }
        public Nullable<decimal> Bac03 { get; set; }
        public Nullable<decimal> Bac04 { get; set; }
        public Nullable<decimal> Bac05 { get; set; }
        public Nullable<decimal> Bac06 { get; set; }
        public Nullable<decimal> Bac07 { get; set; }
        public Nullable<decimal> Bac08 { get; set; }
        public Nullable<decimal> Bac09 { get; set; }
        public Nullable<decimal> Bac10 { get; set; }
        public Nullable<decimal> Bac11 { get; set; }
        public Nullable<decimal> Bac12 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrNhanVien> HrNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrNhanVien> HrNhanVien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrNhanVien> HrNhanVien2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrNhanVien> HrNhanVien3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPSBHXH> HrPSBHXH { get; set; }
    }
}
