//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrTyLeBHXH
    {
        public Nullable<System.DateTime> NgayTu { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<decimal> TyLeBHXH { get; set; }
        public Nullable<decimal> TyLeBHXHNLD { get; set; }
        public Nullable<decimal> TyLeBHYT { get; set; }
        public Nullable<decimal> TyLeBHYTNLD { get; set; }
        public Nullable<decimal> TyLeBHTN { get; set; }
        public Nullable<decimal> TyLeBHTNNLD { get; set; }
        public Nullable<decimal> TyLeKPCD { get; set; }
        public Nullable<decimal> TyLeKPCDNLD { get; set; }
        public System.Guid TyLeBHXHID { get; set; }
    }
}
