//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuongKyLuat
    {
        public System.Guid MaNhanVien { get; set; }
        public Nullable<decimal> STT { get; set; }
        public string LoaiKTKL { get; set; }
        public Nullable<decimal> IDKTKL { get; set; }
        public string Nam { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> IDPhongBan { get; set; }
    }
}
