//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListCommunes
    {
        public decimal CommuneID { get; set; }
        public string CommuneCode { get; set; }
        public string CommuneName { get; set; }
        public Nullable<decimal> DistrictID { get; set; }
    
        public virtual ListDistricts ListDistricts { get; set; }
    }
}
