//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListNoiKCB
    {
        public string MaNoiKCB { get; set; }
        public string TenNoiKCB { get; set; }
        public string MaTinh { get; set; }
        public string MaKCBDayDu { get; set; }
    
        public virtual ListTinh ListTinh { get; set; }
    }
}
