//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListXaPhuong
    {
        public decimal XaPhuongID { get; set; }
        public string MaXaPhuong { get; set; }
        public string TenXaPhuong { get; set; }
        public Nullable<decimal> QuanHuyenID { get; set; }
    
        public virtual ListQuanHuyen ListQuanHuyen { get; set; }
    }
}
