//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLogs
    {
        public System.Guid LogID { get; set; }
        public string ErrorMessage { get; set; }
        public string EventType { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string UserID { get; set; }
        public string Postion { get; set; }
    
        public virtual SysUsers SysUsers { get; set; }
    }
}
