//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysUsers()
        {
            this.SysLogs = new HashSet<SysLogs>();
            this.SysUserRoles = new HashSet<SysUserRoles>();
            this.SysUserSettings = new HashSet<SysUserSettings>();
        }
    
        public string UserID { get; set; }
        public string Pwd { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<System.DateTime> LastPwdChange { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> MaNhanVien { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual HrNhanVien HrNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysLogs> SysLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserRoles> SysUserRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysUserSettings> SysUserSettings { get; set; }
    }
}
