//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserSettings
    {
        public System.Guid UserSettingID { get; set; }
        public string UserID { get; set; }
        public string Setting1 { get; set; }
        public string Setting2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual SysUsers SysUsers { get; set; }
    }
}
