//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHXH.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysUserRoles
    {
        public System.Guid UserRoleID { get; set; }
        public string UserID { get; set; }
        public string RoleID { get; set; }
        public string Descriptions { get; set; }
        public Nullable<System.Guid> GrantedUserID { get; set; }
        public Nullable<System.DateTime> GrantedDate { get; set; }
    
        public virtual SysUsers SysUsers { get; set; }
    }
}
